import type { KeyboardParameter } from "../../../shared/types.js";

export function createSceneParams(): Record<string, KeyboardParameter> {
  return {
    // Scene Common
    scene_level: {
      name: "Scene Level",
      section: "scene-common",
      sysexAddress: [0x00, 0x00, 0x00, 0x10],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 127,
      type: "continuous",
      description: "Controls the overall output level of the scene.",
      encoding: { kind: "raw" },
    },

    // Scene Part
    part_switch: {
      name: "Part Switch",
      section: "scene-part",
      sysexAddress: [0x00, 0x00, 0x00, 0x00],
      sysexSize: 1,
      min: 0,
      max: 1,
      defaultValue: 1,
      type: "toggle",
      labels: { 0: "OFF", 1: "ON" },
      description: "Enables or disables this part within the scene.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_mute: {
      name: "Part Mute",
      section: "scene-part",
      sysexAddress: [0x00, 0x00, 0x00, 0x01],
      sysexSize: 1,
      min: 0,
      max: 2,
      defaultValue: 0,
      type: "discrete",
      labels: { 0: "OFF", 1: "MUTE" },
      description: "Mutes this part within the scene.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_level: {
      name: "Part Level",
      section: "scene-part",
      cc: 7,
      sysexAddress: [0x00, 0x00, 0x00, 0x05],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 100,
      type: "continuous",
      description: "Controls the volume level of this part within the scene.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_pan: {
      name: "Part Pan",
      section: "scene-part",
      cc: 10,
      sysexAddress: [0x00, 0x00, 0x00, 0x06],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Controls the stereo pan position of this part within the scene.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_coarse_tune: {
      name: "Part Coarse Tune",
      section: "scene-part",
      sysexAddress: [0x00, 0x00, 0x00, 0x07],
      sysexSize: 1,
      min: 16,
      max: 112,
      defaultValue: 64,
      type: "continuous",
      description: "Adjusts the coarse pitch tuning (in semitones) of this part.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_mono_poly: {
      name: "Part Mono/Poly",
      section: "scene-part",
      sysexAddress: [0x00, 0x00, 0x00, 0x09],
      sysexSize: 1,
      min: 0,
      max: 2,
      defaultValue: 0,
      type: "discrete",
      labels: { 0: "MONO", 1: "POLY", 2: "TONE" },
      description: "Sets the polyphony mode for this part: mono, poly, or tone.",
      encoding: { kind: "raw" },
      perPart: true,
    },

    // Scene Modify
    part_cutoff_offset: {
      name: "Part Cutoff Offset",
      section: "scene-modify",
      sysexAddress: [0x00, 0x00, 0x00, 0x0f],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Offsets the filter cutoff frequency for this part at the scene level.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_resonance_offset: {
      name: "Part Resonance Offset",
      section: "scene-modify",
      sysexAddress: [0x00, 0x00, 0x00, 0x10],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Offsets the filter resonance for this part at the scene level.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_attack_offset: {
      name: "Part Attack Offset",
      section: "scene-modify",
      sysexAddress: [0x00, 0x00, 0x00, 0x11],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Offsets the envelope attack time for this part at the scene level.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_decay_offset: {
      name: "Part Decay Offset",
      section: "scene-modify",
      sysexAddress: [0x00, 0x00, 0x00, 0x12],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Offsets the envelope decay time for this part at the scene level.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    part_release_offset: {
      name: "Part Release Offset",
      section: "scene-modify",
      sysexAddress: [0x00, 0x00, 0x00, 0x13],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Offsets the envelope release time for this part at the scene level.",
      encoding: { kind: "raw" },
      perPart: true,
    },

    // Scene Chorus
    chorus_switch: {
      name: "Chorus Switch",
      section: "scene-chorus",
      sysexAddress: [0x00, 0x50, 0x00, 0x00],
      sysexSize: 1,
      min: 0,
      max: 1,
      defaultValue: 0,
      type: "toggle",
      labels: { 0: "OFF", 1: "ON" },
      description: "Enables or disables the scene-level chorus effect.",
      encoding: { kind: "raw" },
    },
    chorus_level: {
      name: "Chorus Level",
      section: "scene-chorus",
      sysexAddress: [0x00, 0x50, 0x00, 0x02],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Controls the output level of the scene-level chorus effect.",
      encoding: { kind: "raw" },
    },

    // Scene Delay
    delay_switch: {
      name: "Delay Switch",
      section: "scene-delay",
      sysexAddress: [0x00, 0x51, 0x00, 0x00],
      sysexSize: 1,
      min: 0,
      max: 1,
      defaultValue: 0,
      type: "toggle",
      labels: { 0: "OFF", 1: "ON" },
      description: "Enables or disables the scene-level delay effect.",
      encoding: { kind: "raw" },
    },
    delay_level: {
      name: "Delay Level",
      section: "scene-delay",
      sysexAddress: [0x00, 0x51, 0x00, 0x02],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Controls the output level of the scene-level delay effect.",
      encoding: { kind: "raw" },
    },

    // Scene Reverb
    reverb_switch: {
      name: "Reverb Switch",
      section: "scene-reverb",
      sysexAddress: [0x00, 0x52, 0x00, 0x00],
      sysexSize: 1,
      min: 0,
      max: 1,
      defaultValue: 0,
      type: "toggle",
      labels: { 0: "OFF", 1: "ON" },
      description: "Enables or disables the scene-level reverb effect.",
      encoding: { kind: "raw" },
    },
    reverb_level: {
      name: "Reverb Level",
      section: "scene-reverb",
      sysexAddress: [0x00, 0x52, 0x00, 0x02],
      sysexSize: 1,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Controls the output level of the scene-level reverb effect.",
      encoding: { kind: "raw" },
    },

    // Scene Drive
    drive_switch: {
      name: "Drive Switch",
      section: "scene-drive",
      sysexAddress: [0x00, 0x53, 0x00, 0x04],
      sysexSize: 1,
      min: 0,
      max: 1,
      defaultValue: 0,
      type: "toggle",
      labels: { 0: "OFF", 1: "ON" },
      description: "Enables or disables the scene-level drive effect.",
      encoding: { kind: "raw" },
    },
  };
}
