import type { KeyboardParameter } from "../../../../shared/types.js";
import { JunoXEngine } from "./engine-types.js";

export const ANALOG_SYNTH_ENGINE = JunoXEngine.AnalogSynth;

export function createAnalogSynthParams(): Record<string, KeyboardParameter> {
  return {
    // ── LFO ─────────────────────────────────────────────────────────────────
    as_lfo_waveform: {
      name: "LFO Waveform",
      section: "lfo",
      cc: 35,
      min: 0,
      max: 3,
      defaultValue: 0,
      type: "discrete",
      labels: { 0: "SIN", 1: "SAW-DW", 2: "SQR", 3: "S&H" },
      description: "Selects the LFO waveform shape used for modulation.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_lfo_rate: {
      name: "LFO Rate",
      displayName: "RATE",
      section: "lfo",
      cc: 29,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the speed of the LFO oscillation.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_lfo_delay_time: {
      name: "LFO Delay Time",
      displayName: "DLY",
      section: "lfo",
      cc: 27,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the delay before the LFO effect kicks in after a note is played.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_lfo_sync: {
      name: "LFO Sync",
      displayName: "SYNC",
      section: "lfo",
      cc: 117,
      min: 0,
      max: 1,
      defaultValue: 0,
      type: "toggle",
      labels: { 0: "OFF", 1: "ON" },
      description: "Enables synchronization of the LFO rate to MIDI clock tempo.",
      encoding: { kind: "raw" },
      perPart: true,
    },

    // ── OSC ─────────────────────────────────────────────────────────────────
    as_osc_pitch: {
      name: "OSC Pitch",
      section: "osc",
      cc: 20,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Adjusts the coarse pitch of the oscillator in semitones.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_osc_detune: {
      name: "OSC Detune",
      section: "osc",
      cc: 21,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Fine-tunes the oscillator pitch for chorus/detuning effects.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_pw_level: {
      name: "PW Level / SSAW Level",
      section: "osc",
      cc: 16,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the level of the pulse-width (square) waveform or Super SAW sub-oscillator.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_saw_level: {
      name: "SAW Level",
      section: "osc",
      cc: 17,
      min: 0,
      max: 127,
      defaultValue: 127,
      type: "continuous",
      description: "Sets the level of the sawtooth waveform in the oscillator mix.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_sub_level: {
      name: "SUB Level",
      section: "osc",
      cc: 18,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the level of the sub-oscillator (one octave below the main OSC).",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_noise_level: {
      name: "Noise Level",
      section: "osc",
      cc: 19,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the level of white noise in the oscillator mix.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_super_saw: {
      name: "Super SAW",
      section: "osc",
      cc: 46,
      min: 0,
      max: 1,
      defaultValue: 0,
      type: "toggle",
      labels: { 0: "OFF", 1: "ON" },
      description: "Enables Super SAW mode, layering multiple detuned sawtooth oscillators.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_osc_lfo_mod: {
      name: "OSC LFO Mod",
      section: "osc",
      cc: 26,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the depth of LFO modulation applied to the oscillator pitch (vibrato).",
      encoding: { kind: "raw" },
      perPart: true,
    },

    // ── HPF ─────────────────────────────────────────────────────────────────
    as_hpf_step: {
      name: "HPF Step",
      section: "hpf",
      cc: 79,
      min: 0,
      max: 3,
      defaultValue: 0,
      type: "discrete",
      labels: { 0: "0", 1: "1", 2: "2", 3: "3" },
      description: "Sets the high-pass filter cutoff step (0 = off, 3 = highest cutoff).",
      encoding: { kind: "raw" },
      perPart: true,
    },

    // ── Filter ───────────────────────────────────────────────────────────────
    as_vintage_flt_type: {
      name: "Vintage Filter Type",
      section: "filter",
      cc: 108,
      min: 0,
      max: 2,
      defaultValue: 0,
      type: "discrete",
      labels: { 0: "R", 1: "M", 2: "S" },
      description: "Selects the vintage filter character: R (Roland), M (Moog-style), or S (sharp).",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_cutoff: {
      name: "Cutoff",
      displayName: "CUT",
      section: "filter",
      cc: 3,
      min: 0,
      max: 127,
      defaultValue: 127,
      type: "continuous",
      description: "Sets the VCF cutoff frequency; higher values let more harmonics through.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_resonance: {
      name: "Resonance",
      displayName: "RES",
      section: "filter",
      cc: 9,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the VCF resonance (Q); higher values add a peak at the cutoff frequency.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_flt_env_depth: {
      name: "Filter Env Depth",
      section: "filter",
      cc: 81,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets how much the envelope modulates the filter cutoff frequency.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_flt_key_follow: {
      name: "Filter Key Follow",
      section: "filter",
      cc: 122,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets how much keyboard pitch tracking is applied to the filter cutoff.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_flt_lfo_mod: {
      name: "Filter LFO Mod",
      section: "filter",
      cc: 28,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the depth of LFO modulation applied to the filter cutoff (filter wah).",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_flt_vsens: {
      name: "Filter Velocity Sens",
      section: "filter",
      cc: 53,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets how much key velocity affects the filter cutoff frequency.",
      encoding: { kind: "raw" },
      perPart: true,
    },

    // ── AMP ──────────────────────────────────────────────────────────────────
    as_amp_level: {
      name: "AMP Level",
      section: "amp",
      cc: 110,
      min: 0,
      max: 127,
      defaultValue: 100,
      type: "continuous",
      description: "Sets the overall output level of the VCA amplifier.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_amp_lfo_mod: {
      name: "AMP LFO Mod",
      section: "amp",
      cc: 30,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the depth of LFO modulation applied to the VCA level (tremolo).",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_amp_vsens: {
      name: "AMP Velocity Sens",
      section: "amp",
      cc: 54,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets how much key velocity affects the VCA output level.",
      encoding: { kind: "raw" },
      perPart: true,
    },

    // ── ENV ──────────────────────────────────────────────────────────────────
    as_env_attack: {
      name: "ENV Attack",
      section: "env",
      cc: 89,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the attack time of the ADSR envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_env_decay: {
      name: "ENV Decay",
      section: "env",
      cc: 90,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Sets the decay time of the ADSR envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_env_sustain: {
      name: "ENV Sustain",
      section: "env",
      cc: 102,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Sets the sustain level of the ADSR envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_env_release: {
      name: "ENV Release",
      section: "env",
      cc: 103,
      min: 0,
      max: 127,
      defaultValue: 32,
      type: "continuous",
      description: "Sets the release time of the ADSR envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_penv_attack: {
      name: "Pitch Env Attack",
      section: "env",
      cc: 83,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the attack time of the pitch envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_penv_decay: {
      name: "Pitch Env Decay",
      section: "env",
      cc: 80,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the decay time of the pitch envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_penv_sustain: {
      name: "Pitch Env Sustain",
      section: "env",
      cc: 85,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the sustain level of the pitch envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_penv_release: {
      name: "Pitch Env Release",
      section: "env",
      cc: 86,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the release time of the pitch envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },

    // ── Performance ──────────────────────────────────────────────────────────
    as_bend_pitch: {
      name: "Bend Pitch",
      section: "performance",
      cc: 41,
      min: 0,
      max: 127,
      defaultValue: 2,
      type: "continuous",
      description: "Sets the pitch bend range in semitones.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_bend_filter: {
      name: "Bend Filter",
      section: "performance",
      cc: 14,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Sets how much the pitch bend wheel modulates the filter cutoff.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_porta_mode: {
      name: "Portamento Mode",
      section: "performance",
      cc: 118,
      min: 0,
      max: 1,
      defaultValue: 0,
      type: "toggle",
      labels: { 0: "OFF", 1: "ON" },
      description: "Enables portamento (glide) between notes.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_porta_time: {
      name: "Portamento Time",
      section: "performance",
      cc: 5,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the speed of portamento glide between notes.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    as_key_mode: {
      name: "Key Mode",
      section: "performance",
      cc: 119,
      min: 0,
      max: 3,
      defaultValue: 0,
      type: "discrete",
      labels: { 0: "POLY", 1: "SOLO", 2: "UNISON", 3: "SL-UNISON" },
      description: "Sets the key/voice assignment mode: polyphonic, monophonic solo, unison, or solo unison.",
      encoding: { kind: "raw" },
      perPart: true,
    },
  };
}
