export { AudioAnalysisClient } from "./client.js";
export type { AudioAnalysisClientOptions, RequestOptions } from "./client.js";
export type {
  ImportRequest,
  ImportAudioResult,
  StemsRequest,
  StemSeparateResult,
  StemFile,
  StemPreset,
  StructureRequest,
  StructureAnalyzeResult,
  StructureSegment,
  TranscribeRequest,
  NoteTranscribeServiceResult,
  TriageSection,
  TriageRequest,
  NoteTriageBySectionsServiceResult,
  ProgressEvent,
  ResultEvent,
  ErrorEvent,
  StemsEvent,
  StructureEvent,
  TranscribeEvent,
  TriageEvent,
} from "./types.js";
