import type { KeyboardParameter } from "../../../../shared/types.js";
import { JunoXEngine } from "./engine-types.js";

export const JUNO_X_MODEL_ENGINE = JunoXEngine.JunoXModel;

export function createJunoXModelParams(): Record<string, KeyboardParameter> {
  return {
    lfo_waveform: {
      name: "LFO Waveform",
      section: "lfo",
      cc: 35,
      min: 0,
      max: 3,
      defaultValue: 0,
      type: "discrete",
      labels: { 0: "SIN", 1: "SAW-DW", 2: "SQR", 3: "S&H" },
      description: "Selects the waveform shape for the LFO modulation source.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    lfo_rate: {
      name: "LFO Rate",
      section: "lfo",
      cc: 29,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Controls the speed of the LFO oscillation.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    lfo_delay_time: {
      name: "LFO Delay Time",
      section: "lfo",
      cc: 27,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the delay before the LFO effect kicks in after a note is played.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    osc_lfo_mod: {
      name: "OSC LFO Mod",
      section: "osc",
      cc: 26,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Controls the depth of LFO modulation applied to the oscillator pitch.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    pw_level: {
      name: "PW Level",
      section: "osc",
      cc: 16,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the level of the pulse-width waveform in the oscillator mix.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    saw_level: {
      name: "SAW Level",
      section: "osc",
      cc: 17,
      min: 0,
      max: 127,
      defaultValue: 127,
      type: "continuous",
      description: "Sets the level of the sawtooth waveform in the oscillator mix.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    sub_level: {
      name: "SUB Level",
      section: "osc",
      cc: 18,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the level of the sub-oscillator (one octave below) in the oscillator mix.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    noise_level: {
      name: "Noise Level",
      section: "osc",
      cc: 19,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the level of the noise source in the oscillator mix.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    cutoff: {
      name: "Cutoff",
      section: "filter",
      cc: 3,
      min: 0,
      max: 127,
      defaultValue: 127,
      type: "continuous",
      description: "Controls the cutoff frequency of the low-pass filter.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    resonance: {
      name: "Resonance",
      section: "filter",
      cc: 9,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Controls the resonance (emphasis) at the filter cutoff frequency.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    flt_env_depth: {
      name: "Filter Env Depth",
      section: "filter",
      cc: 81,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets how much the envelope modulates the filter cutoff frequency.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    amp_level: {
      name: "AMP Level",
      section: "amp",
      cc: 110,
      min: 0,
      max: 127,
      defaultValue: 100,
      type: "continuous",
      description: "Controls the overall output level of the amplifier stage.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    env_attack: {
      name: "ENV Attack",
      section: "env",
      cc: 89,
      min: 0,
      max: 127,
      defaultValue: 0,
      type: "continuous",
      description: "Sets the attack time of the amplitude and filter envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    env_decay: {
      name: "ENV Decay",
      section: "env",
      cc: 90,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Sets the decay time of the amplitude and filter envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    env_sustain: {
      name: "ENV Sustain",
      section: "env",
      cc: 102,
      min: 0,
      max: 127,
      defaultValue: 64,
      type: "continuous",
      description: "Sets the sustain level of the amplitude and filter envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    env_release: {
      name: "ENV Release",
      section: "env",
      cc: 103,
      min: 0,
      max: 127,
      defaultValue: 32,
      type: "continuous",
      description: "Sets the release time of the amplitude and filter envelope.",
      encoding: { kind: "raw" },
      perPart: true,
    },
    key_mode: {
      name: "Key Mode",
      section: "performance",
      cc: 119,
      min: 0,
      max: 3,
      defaultValue: 0,
      type: "discrete",
      labels: { 0: "POLY", 1: "SOLO", 2: "UNISON", 3: "SL-UNISON" },
      description: "Selects the keyboard play mode: polyphonic, solo, unison, or solo unison.",
      encoding: { kind: "raw" },
      perPart: true,
    },
  };
}
